# Generated by Django 5.0.4 on 2024-04-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Klines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_time", models.FloatField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume_assets", models.FloatField()),
                ("close_time", models.FloatField()),
                ("volume_actif", models.FloatField()),
                ("number_trades", models.FloatField()),
                ("taker_buy_volume", models.FloatField()),
                ("taker_buy_actif_volume", models.FloatField()),
            ],
        ),
    ]
